extends Node

enum GAME_TYPE {  
	REGULAR,
	ENDLESS  
}  

enum INPUT_TYPE {  
	KEYBOARD,
	MOUSE,
	KEYBOARD_AND_MOUSE,
	SPACE
}  

const INPUT_TYPE_NAMES = {
	INPUT_TYPE.KEYBOARD: "Keyboard",
	INPUT_TYPE.MOUSE: "Mouse",
	INPUT_TYPE.KEYBOARD_AND_MOUSE: "Keyboard + Mouse",
	INPUT_TYPE.SPACE: "Space",
}
